### ISSUE TITLE
add allure environment

### ISSUE THREAD

**Issue by nirtal85** [nirtal85/Selenium-Python-Example#33]
https://github.com/allure-framework/allure-python/issues/96
https://stackoverflow.com/questions/35264335/customize-allure-report-using-pytest-allure-adaptor

**Comment by elias-shoursoh** [comment]
What would you like the allure environment to include?
what to do you mean by before/after all?

**Comment by nirtal85** [comment]
> What would you like the allure environment to include?
> what to do you mean by before/after all?

browser,
base url

**Comment by elias-shoursoh** [comment]
Done

**Comment by nirtal85** [comment]
not yet
